#lang racket
(require "lang.rkt")

(provide (all-defined-out))

(define-localizations
  (appy-Info "Info")
  (appy-Fatal "Fatal")
  (appy-Debug "Debug")
  (appy-Warning "Warning")
  (appy-err-event "[~a] ~a: ~a event number ~a has occurred. Please check the manual for more information. [~a ~a]")
  (appy-command-target-not-found "Command target not found. The target link is stale. Given: ~s.")
  (appy-command-empty-data-field "Empty data field for command. The undo database might be corrupted. Given: ~s")
  (appy-undo-empty-data "Empty data in undo manager. The undo database might be corrupted.")
  (appy-command-numeric-twice "A command numeric id was registered twice - race condition? You may not use make-command concurrently. Command numeric=~s")
  (appy-undo-version-err "An attempt to undo a command from a higher version of the undo manager has failed. Please update the application to the latest version to undo this action. Command numeric=~s")
  (appy-undo-manager-already-open "The undo manager is already open.")
  (appy-undo-manager-closed "The undo manager is closed. Use open-undo-system to initialize it.")
  (appy-maintenance-message "~a is doing maintenance: ~a")
  (appy-maintenance-ended "Maintenance for ~a has ended: ~a")
  (appy-open-db-twice "~a attempted to open a database twice.")
  (appy-use-closed-db "~a attempted to use a closed database.")
  (appy-close-db-twice "~a attempted to close a database twice.")
  (appy-start-clean-preferences "Starting to clean up preferences.")
  (appy-end-clean-preferences "Done cleaning up preferences.")
  (appy-start-clean-undo "Starting to clean up the undo system.")
  (appy-done-clean-undo "Done cleaning up the undo system.")
  (appy-Application "Application")
  (appy-Error "Error")
  (appy-Save-and-Quit "Save & Quit")
  (appy-Continue "Continue")
  (appy-save-and-quit-message "~a\n\nYou should Save & Quit now or may continue at your own risk.")
  (appy-routine-maintenance-message "~a is undergoing routine maintenance. Please do not interrupt this process.")
  (appy-Maintenance "Maintenance")
  (appy-about-title "About ~a")
  (appy-Module "Module")
  (appy-unknown-error "Unknown Error"))